services:
  db:
    image: postgres:18-alpine
    container_name: storeGH-db
    
    restart: always    
    
    volumes:
      - db-data:/etc/data
    
    ports:
      - '5432:5432'
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Neto;1981
      POSTGRES_DB: storeGH

volumes:
  db-data:
